version: "3.8"

services:
  api:
    build:
      dockerfile: ./docker/api.Dockerfile
      context: ./../
    container_name: api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    ports:
      - "8888:8888"
